In [ ]:
import numpy as np
import pandas as pd
import os

In [1]:

root_folder = '~/sfusd-local-data/zones/SFUSD/local_runs/comparisons/'
df = pd.read_csv(os.path.expanduser(f"{root_folder}/comparative_results.csv"))

NameError: name 'pd' is not defined

In [10]:
df['objective_value'] = df['objective_value'].replace(-1, np.nan)
df = df[df['level']== 'BlockGroup']
df

,time_limit,seed,centroids_type,level,frl_dev,racial_dev,optimizer,status,wall_time,objective_value
0,300,42,13-zone-6,BlockGroup,0.2,0.3,cp_int,FEASIBLE,300.823993,259.0
1,60,2025,8-zone-25,BlockGroup,0.2,0.3,cp_bool,FEASIBLE,60.184356,210.0
2,600,1014,6-zone-2,BlockGroup,0.4,0.3,cp_bool,FEASIBLE,600.206913,126.0
3,60,2025,13-zone-6,BlockGroup,0.2,0.3,mip,TIME_LIMIT,60.002120,NaN
4,300,42,6-zone-2,BlockGroup,0.4,0.3,mip,TIME_LIMIT,300.020669,111.0
...,...,...,...,...,...,...,...,...,...,...
268,300,42,8-zone-25,BlockGroup,0.4,0.3,cp_int,FEASIBLE,300.253259,154.0
269,300,2025,13-zone-6,BlockGroup,0.4,0.3,cp_int,FEASIBLE,300.298818,236.0
270,60,42,10-zone-3,BlockGroup,0.2,0.3,cp_int,FEASIBLE,60.313164,209.0
271,600,1014,10-zone-3,BlockGroup,0.4,0.3,cp_bool,FEASIBLE,600.383257,210.0
272,60,2025,6-zone-2,BlockGroup,0.4,0.3,cp_bool,FEASIBLE,60.156351,128.0

In [11]:
grouped_dfs = df.groupby(['seed', 'centroids_type', 'level', 'time_limit','frl_dev', 'racial_dev'], as_index=False)

In [12]:
for name, group in grouped_dfs:
    print(group)
    print("\n")

     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
171          60    42      10-zone-3  BlockGroup      0.2         0.3
261          60    42      10-zone-3  BlockGroup      0.2         0.3
270          60    42      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
171   cp_bool    FEASIBLE  60.485561            235.0
261       mip  TIME_LIMIT  60.010583              NaN
270    cp_int    FEASIBLE  60.313164            209.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
92           60    42      10-zone-3  BlockGroup      0.4         0.3
161          60    42      10-zone-3  BlockGroup      0.4         0.3
182          60    42      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
92     cp_int    FEASIBLE  60.242409            215.0
161       mip  TIME_LIMIT  60.014519              NaN
182   cp_bool    FEASIBLE  60.162849            230.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
131         300    42      10-zone-3  BlockGroup      0.2         0.3
187         300    42      10-zone-3  BlockGroup      0.2         0.3
217         300    42      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
131    cp_int    FEASIBLE  301.272634            214.0
187   cp_bool    FEASIBLE  300.263914            229.0
217       mip  TIME_LIMIT  300.002936              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
168         300    42      10-zone-3  BlockGroup      0.4         0.3
211         300    42      10-zone-3  BlockGroup      0.4         0.3
216         300    42      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
168   cp_bool    FEASIBLE  300.201203            195.0
211       mip  TIME_LIMIT  300.015083              NaN
216    cp_int    FEASIBLE  300.552100            190.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
6           600    42      10-zone-3  BlockGroup      0.2         0.3
86          600    42      10-zone-3  BlockGroup      0.2         0.3
177         600    42      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
6         mip  TIME_LIMIT  600.017892              NaN
86     cp_int    FEASIBLE  600.308163            213.0
177   cp_bool    FEASIBLE  600.266189            206.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
145         600    42      10-zone-3  BlockGroup      0.4         0.3
178         600    42      10-zone-3  BlockGroup      0.4         0.3
264         600    42      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
145       mip  TIME_LIMIT  600.019917              NaN
178   cp_bool    FEASIBLE  600.266550            182.0
264    cp_int    FEASIBLE  600.308300            200.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
95           60    42      13-zone-6  BlockGroup      0.2         0.3
159          60    42      13-zone-6  BlockGroup      0.2         0.3
219          60    42      13-zone-6  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
95    cp_bool    FEASIBLE  60.212193            269.0
159    cp_int    FEASIBLE  60.380855            252.0
219       mip  TIME_LIMIT  60.002436              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
72           60    42      13-zone-6  BlockGroup      0.4         0.3
126          60    42      13-zone-6  BlockGroup      0.4         0.3
202          60    42      13-zone-6  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
72     cp_int    FEASIBLE  60.271990            237.0
126   cp_bool    FEASIBLE  60.210382            221.0
202       mip  TIME_LIMIT  60.002324              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
0           300    42      13-zone-6  BlockGroup      0.2         0.3
116         300    42      13-zone-6  BlockGroup      0.2         0.3
263         300    42      13-zone-6  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
0      cp_int    FEASIBLE  300.823993            259.0
116   cp_bool    FEASIBLE  300.294669            232.0
263       mip  TIME_LIMIT  300.015134              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
105         300    42      13-zone-6  BlockGroup      0.4         0.3
153         300    42      13-zone-6  BlockGroup      0.4         0.3
196         300    42      13-zone-6  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
105   cp_bool    FEASIBLE  300.451632            237.0
153       mip  TIME_LIMIT  300.014419              NaN
196    cp_int    FEASIBLE  300.518670            224.0


    time_limit  seed centroids_type       level  frl_dev  racial_dev  \
57         600    42      13-zone-6  BlockGroup      0.2         0.3
63         600    42      13-zone-6  BlockGroup      0.2         0.3
99         600    42      13-zone-6  BlockGroup      0.2         0.3

   optimizer      status   wall_time  objective_value
57       mip  TIME_LIMIT  600.010918              NaN
63    cp_int    FEASIBLE  600.442181            243.0
99   cp_bool    FEASIBLE  600.639138            251.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
88          600    42      13-zone-6  BlockGroup      0.4         0.3
123         600    42      13-zone-6  BlockGroup      0.4         0.3
149         600    42      13-zone-6  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
88        mip  TIME_LIMIT  600.015152              NaN
123   cp_bool    FEASIBLE  600.243601            224.0
149    cp_int    FEASIBLE  600.379561            239.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
49           60    42      18-zone-7  BlockGroup      0.2         0.3
71           60    42      18-zone-7  BlockGroup      0.2         0.3
107          60    42      18-zone-7  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
49        mip  TIME_LIMIT  60.002871              NaN
71    cp_bool    FEASIBLE  60.275857            353.0
107    cp_int    FEASIBLE  60.290402            389.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
7            60    42      18-zone-7  BlockGroup      0.4         0.3
97           60    42      18-zone-7  BlockGroup      0.4         0.3
257          60    42      18-zone-7  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
7     cp_bool    FEASIBLE  60.263902            314.0
97        mip  TIME_LIMIT  60.003992              NaN
257    cp_int    FEASIBLE  60.273621            306.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
23          300    42      18-zone-7  BlockGroup      0.2         0.3
36          300    42      18-zone-7  BlockGroup      0.2         0.3
237         300    42      18-zone-7  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
23    cp_bool    FEASIBLE  300.257968            336.0
36        mip  TIME_LIMIT  300.013564              NaN
237    cp_int    FEASIBLE  300.323671            301.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
56          300    42      18-zone-7  BlockGroup      0.4         0.3
111         300    42      18-zone-7  BlockGroup      0.4         0.3
120         300    42      18-zone-7  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
56    cp_bool    FEASIBLE  300.334850            262.0
111    cp_int    FEASIBLE  300.632755            281.0
120       mip  TIME_LIMIT  300.008215              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
67          600    42      18-zone-7  BlockGroup      0.2         0.3
241         600    42      18-zone-7  BlockGroup      0.2         0.3
246         600    42      18-zone-7  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
67    cp_bool    FEASIBLE  600.363273            310.0
241       mip  TIME_LIMIT  600.031763              NaN
246    cp_int    FEASIBLE  600.339626            299.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
10          600    42      18-zone-7  BlockGroup      0.4         0.3
98          600    42      18-zone-7  BlockGroup      0.4         0.3
183         600    42      18-zone-7  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
10    cp_bool    FEASIBLE  601.300176            273.0
98     cp_int    FEASIBLE  600.334587            279.0
183       mip  TIME_LIMIT  600.012400              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
147          60    42       6-zone-2  BlockGroup      0.2         0.3
152          60    42       6-zone-2  BlockGroup      0.2         0.3
244          60    42       6-zone-2  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
147    cp_int    FEASIBLE  60.237678            134.0
152   cp_bool    FEASIBLE  60.179637            131.0
244       mip  TIME_LIMIT  60.014567              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
174          60    42       6-zone-2  BlockGroup      0.4         0.3
204          60    42       6-zone-2  BlockGroup      0.4         0.3
228          60    42       6-zone-2  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
174       mip  TIME_LIMIT  60.028391            133.0
204   cp_bool    FEASIBLE  60.407751            125.0
228    cp_int    FEASIBLE  60.281459            124.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
18          300    42       6-zone-2  BlockGroup      0.2         0.3
104         300    42       6-zone-2  BlockGroup      0.2         0.3
144         300    42       6-zone-2  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
18    cp_bool    FEASIBLE  300.203536            125.0
104    cp_int    FEASIBLE  300.211520            118.0
144       mip  TIME_LIMIT  300.019781            117.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
4           300    42       6-zone-2  BlockGroup      0.4         0.3
59          300    42       6-zone-2  BlockGroup      0.4         0.3
252         300    42       6-zone-2  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
4         mip  TIME_LIMIT  300.020669            111.0
59    cp_bool    FEASIBLE  300.138627            125.0
252    cp_int    FEASIBLE  300.414373            123.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
20          600    42       6-zone-2  BlockGroup      0.2         0.3
70          600    42       6-zone-2  BlockGroup      0.2         0.3
199         600    42       6-zone-2  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
20     cp_int    FEASIBLE  600.256452            130.0
70    cp_bool    FEASIBLE  600.221413            125.0
199       mip  TIME_LIMIT  600.020472            117.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
5           600    42       6-zone-2  BlockGroup      0.4         0.3
203         600    42       6-zone-2  BlockGroup      0.4         0.3
227         600    42       6-zone-2  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
5     cp_bool    FEASIBLE  600.175603            125.0
203    cp_int    FEASIBLE  600.243599            123.0
227       mip  TIME_LIMIT  600.018008            111.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
13           60    42      8-zone-25  BlockGroup      0.2         0.3
44           60    42      8-zone-25  BlockGroup      0.2         0.3
221          60    42      8-zone-25  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
13    cp_bool    FEASIBLE  60.472663            197.0
44        mip  TIME_LIMIT  60.003668              NaN
221    cp_int    FEASIBLE  60.271369            196.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
62           60    42      8-zone-25  BlockGroup      0.4         0.3
109          60    42      8-zone-25  BlockGroup      0.4         0.3
134          60    42      8-zone-25  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
62    cp_bool    FEASIBLE  60.507751            220.0
109       mip  TIME_LIMIT  60.006814              NaN
134    cp_int    FEASIBLE  60.249318            185.0


    time_limit  seed centroids_type       level  frl_dev  racial_dev  \
25         300    42      8-zone-25  BlockGroup      0.2         0.3
68         300    42      8-zone-25  BlockGroup      0.2         0.3
87         300    42      8-zone-25  BlockGroup      0.2         0.3

   optimizer      status   wall_time  objective_value
25       mip  TIME_LIMIT  300.015213              NaN
68   cp_bool    FEASIBLE  300.192287            166.0
87    cp_int    FEASIBLE  300.167361            223.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
11          300    42      8-zone-25  BlockGroup      0.4         0.3
128         300    42      8-zone-25  BlockGroup      0.4         0.3
268         300    42      8-zone-25  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
11    cp_bool    FEASIBLE  300.363258            174.0
128       mip  TIME_LIMIT  300.011298              NaN
268    cp_int    FEASIBLE  300.253259            154.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
22          600    42      8-zone-25  BlockGroup      0.2         0.3
143         600    42      8-zone-25  BlockGroup      0.2         0.3
236         600    42      8-zone-25  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
22    cp_bool    FEASIBLE  600.259589            179.0
143    cp_int    FEASIBLE  601.216711            155.0
236       mip  TIME_LIMIT  600.014757              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
55          600    42      8-zone-25  BlockGroup      0.4         0.3
193         600    42      8-zone-25  BlockGroup      0.4         0.3
230         600    42      8-zone-25  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
55    cp_bool    FEASIBLE  600.227559            165.0
193       mip  TIME_LIMIT  600.017742              NaN
230    cp_int    FEASIBLE  600.284682            166.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
156          60  1014      10-zone-3  BlockGroup      0.2         0.3
176          60  1014      10-zone-3  BlockGroup      0.2         0.3
194          60  1014      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
156   cp_bool    FEASIBLE  60.163262            228.0
176    cp_int    FEASIBLE  60.332775            208.0
194       mip  TIME_LIMIT  60.012975              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
51           60  1014      10-zone-3  BlockGroup      0.4         0.3
195          60  1014      10-zone-3  BlockGroup      0.4         0.3
231          60  1014      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
51     cp_int    FEASIBLE  60.322253            223.0
195   cp_bool    FEASIBLE  60.169784            219.0
231       mip  TIME_LIMIT  60.016034              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
35          300  1014      10-zone-3  BlockGroup      0.2         0.3
112         300  1014      10-zone-3  BlockGroup      0.2         0.3
167         300  1014      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
35     cp_int    FEASIBLE  300.327301            201.0
112   cp_bool    FEASIBLE  300.240988            214.0
167       mip  TIME_LIMIT  300.014456              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
108         300  1014      10-zone-3  BlockGroup      0.4         0.3
188         300  1014      10-zone-3  BlockGroup      0.4         0.3
253         300  1014      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
108   cp_bool    FEASIBLE  300.245791            192.0
188    cp_int    FEASIBLE  300.644485            203.0
253       mip  TIME_LIMIT  300.011426              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
81          600  1014      10-zone-3  BlockGroup      0.2         0.3
218         600  1014      10-zone-3  BlockGroup      0.2         0.3
220         600  1014      10-zone-3  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
81     cp_int    FEASIBLE  600.262478            238.0
218   cp_bool    FEASIBLE  600.785257            216.0
220       mip  TIME_LIMIT  600.018750              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
201         600  1014      10-zone-3  BlockGroup      0.4         0.3
265         600  1014      10-zone-3  BlockGroup      0.4         0.3
271         600  1014      10-zone-3  BlockGroup      0.4         0.3

    optimizer      status   wall_time  objective_value
201       mip  TIME_LIMIT  600.013447              NaN
265    cp_int    FEASIBLE  600.303446            192.0
271   cp_bool    FEASIBLE  600.383257            210.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
82           60  1014      13-zone-6  BlockGroup      0.2         0.3
150          60  1014      13-zone-6  BlockGroup      0.2         0.3
255          60  1014      13-zone-6  BlockGroup      0.2         0.3

    optimizer      status  wall_time  objective_value
82    cp_bool    FEASIBLE  60.174620            250.0
150       mip  TIME_LIMIT  60.002481              NaN
255    cp_int    FEASIBLE  60.243756            248.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
110          60  1014      13-zone-6  BlockGroup      0.4         0.3
138          60  1014      13-zone-6  BlockGroup      0.4         0.3
267          60  1014      13-zone-6  BlockGroup      0.4         0.3

    optimizer      status  wall_time  objective_value
110    cp_int    FEASIBLE  60.244286            230.0
138   cp_bool    FEASIBLE  60.189904            231.0
267       mip  TIME_LIMIT  60.027979              NaN


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
121         300  1014      13-zone-6  BlockGroup      0.2         0.3
180         300  1014      13-zone-6  BlockGroup      0.2         0.3
186         300  1014      13-zone-6  BlockGroup      0.2         0.3

    optimizer      status   wall_time  objective_value
121    cp_int    FEASIBLE  300.398913            254.0
180       mip  TIME_LIMIT  300.009495              NaN
186   cp_bool    FEASIBLE  300.235475            259.0


     time_limit  seed centroids_type       level  frl_dev  racial_dev  \
169         300  1014      13-zone-6  BlockGroup      0.4         0.3
240         300  1014      13-zone-6  BlockGroup      0.4         0.3
243         300  1014      13-zone-6  BlockGroup      0.4         0.3


In [13]:
# find average percent difference in objective value between cp_int and cp_bool for each group
results = []
for name, group in grouped_dfs:
    cp_int = group[group['optimizer'] == 'cp_int']['objective_value'].values
    cp_bool = group[group['optimizer'] == 'cp_bool']['objective_value'].values
    mip = group[group['optimizer'] == 'mip']['objective_value'].values
    bool_gap = np.nan
    mip_gap = np.nan
    # bool gap is the percent difference between cp_bool and cp_int
    # mip gap is the percent difference between mip and cp_int
    if len(cp_int) > 0 and len(cp_bool) > 0:
        bool_gap = (cp_bool[0] - cp_int[0]) / cp_int[0] * 100
    if len(cp_int) > 0 and len(mip) > 0:
        mip_gap = (mip[0] - cp_int[0]) / cp_int[0] * 100
    results.append(list(name) + [cp_int[0] if len(cp_int) > 0 else np.nan,
                                  cp_bool[0] if len(cp_bool) > 0 else np.nan,
                                  mip[0] if len(mip) > 0 else np.nan,
                                  bool_gap, mip_gap])

results_df = pd.DataFrame(results, columns=['seed', 'centroids_type', 'level', 'time_limit','frl_dev', 'racial_dev', 'cp_int_obj', 'cp_bool_obj', 'mip_obj', 'bool_gap', 'mip_gap'])

In [14]:
results_df

,seed,centroids_type,level,time_limit,frl_dev,racial_dev,cp_int_obj,cp_bool_obj,mip_obj,bool_gap,mip_gap
0,42,10-zone-3,BlockGroup,60,0.2,0.3,209.0,235.0,NaN,12.440191,NaN
1,42,10-zone-3,BlockGroup,60,0.4,0.3,215.0,230.0,NaN,6.976744,NaN
2,42,10-zone-3,BlockGroup,300,0.2,0.3,214.0,229.0,NaN,7.009346,NaN
3,42,10-zone-3,BlockGroup,300,0.4,0.3,190.0,195.0,NaN,2.631579,NaN
4,42,10-zone-3,BlockGroup,600,0.2,0.3,213.0,206.0,NaN,-3.286385,NaN
...,...,...,...,...,...,...,...,...,...,...,...
85,2025,8-zone-25,BlockGroup,60,0.4,0.3,174.0,214.0,NaN,22.988506,NaN
86,2025,8-zone-25,BlockGroup,300,0.2,0.3,162.0,169.0,NaN,4.320988,NaN
87,2025,8-zone-25,BlockGroup,300,0.4,0.3,167.0,177.0,190.0,5.988024,13.772455
88,2025,8-zone-25,BlockGroup,600,0.2,0.3,178.0,175.0,NaN,-1.685393,NaN
89,2025,8-zone-25,BlockGroup,600,0.4,0.3,171.0,177.0,148.0,3.508772,-13.450292